# Site settings
title: collamo - Koji Miyauchi
email: koji@collamo.jp
url: https://collamo.github.io
description: "Koji Miyauchi is a full stack engineer."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Koji Miyauchi
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/collamo
  - title: bitbucket
    url: https://bitbucket.org/collamo/
  - title: linkedin
    url: https://www.linkedin.com/pub/koji-miyauchi/2a/a98/381
  - title: twitter
    url: http://twitter.com/KojiMiyauchi

# Postal address (add as many lines as necessary)
address:
  - line: Canada
  - line: North York, Ontario

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
